# Generated by Django 3.1.1 on 2020-09-21 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bastidor', models.TextField(max_length=17)),
                ('potencia', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cilindraje', models.IntegerField()),
                ('modelo', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=19)),
                ('concesionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.servicio')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.marca')),
            ],
        ),
    ]
