# Generated by Django 3.1.1 on 2020-09-21 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20200921_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='bastidor',
        ),
    ]
