# Generated by Django 3.1.1 on 2020-09-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20200921_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipamiento'),
        ),
    ]
